name: 'Workflow PR Labeler'
description: 'Update and assign pull request labels given configuration'
author: 'igoroctaviano'
inputs: 
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
  CONFIG_PATH:
    description: 'The path for the config file (root)'
runs:
  using: 'node12'
  main: 'lib/main.js'
